### ISSUE TITLE
Can we add screenshots to the report for failed test cases

### ISSUE THREAD

**Issue by dinesha87** [grasshopper7/extentreports-cucumber6-adapter#1]
Now it's only saving the screenshot in a seperate folder, but i want to display them in the report. Is there a way to show the screenshots in the report?

**Comment by grasshopper7** [comment]
It should be displaying in the report. Will have a look. Which report are you using?

**Comment by dinesha87** [comment]
I used html report even i tried with spark but it was not displaying.

**Comment by grasshopper7** [comment]
Do u have these settings in your extent.properties? I tried it and it works for me.

> screenshot.dir=test-output/
screenshot.rel.path=../

Refer to this sample implementation - https://github.com/grasshopper7/cuke6-extent-adapter-report

**Comment by dinesha87** [comment]
I updated with 

screenshot.rel.path=../

But still i'm not getting it, will check with the sample implementation.

**Comment by dinesha87** [comment]
It worked but had to use below code,

ExtentCucumberAdapter.addTestStepScreenCaptureFromPath();
