### ISSUE TITLE
Option to Configure the Background of Steps in Spark Report in extentreports-cucumber6-adapter 2.0.0

### ISSUE THREAD

**Issue by tbc-home** [grasshopper7/extentreports-cucumber6-adapter#12]
Hi all,

Previously with version extentreports-cucumber6-adapter 1.2.0, Spark/HTML report had a white background for all Steps with Green/Red Tick to represent the Pass and Fail or Skip (Blue), this was a approach since long for extent report. This was a more cleaner GUI for the report. 

Can we get option to apply that format?

**Comment by grasshopper7** [comment]
U can try switching the `theme` option in the config xml to standard. The adapter just uses the Extent Spark report. To raise issues regarding changes to it, raise an issue here - https://github.com/extent-framework/extentreports-java/issues
