### ISSUE TITLE
Horizontal scroll bar issue in Spark report when we have 4 or morefeature files with multiple scenarios.

### ISSUE THREAD

**Issue by tbc-home** [grasshopper7/extentreports-cucumber6-adapter#13]
Horizontal scroll bar issue in Spark report when we have 4 or more feature files with multiple scenarios.

**Comment by grasshopper7** [comment]
Can u add a screenshot, easier to understand

**Comment by tbc-home** [comment]
![screenshot](https://user-images.githubusercontent.com/28675824/96459975-5c427c00-1240-11eb-992f-8aff9b309c95.png)

**Comment by grasshopper7** [comment]
Not sure I understand the issue. U have to mention more details.

**Comment by tbc-home** [comment]
The problem is that there is no horizontal scroll bar coming on load. there are multiple scenarios which i am not able to scroll to. Attached Sample Report.
[ReportSpark.zip](https://github.com/grasshopper7/extentreports-cucumber6-adapter/files/5409121/ReportSpark.zip)

**Comment by grasshopper7** [comment]
U will have to check with the extentreport developer. I can look at data or content issues in the report but almost all of the time presentation or view issues I cannot address. Thx
