### ISSUE TITLE
Method to get the Status of Summary/Execution count

### ISSUE THREAD

**Issue by salunkhe-ravi** [grasshopper7/extentreports-cucumber6-adapter#14]
Hello @grasshopper7 ,

Is there a way or method to retrieve the count for below items from the report:
Total Tests
Passed
Failed
?

**Comment by grasshopper7** [comment]
There is a class which exposes methods you can use - https://github.com/extent-framework/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/model/ReportStats.java

This is a variable in the Report class - https://github.com/extent-framework/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/model/Report.java
