### ISSUE TITLE
Parameterised scenario names appear as blank in extent reports

### ISSUE THREAD

**Issue by ritunegi04** [grasshopper7/extentreports-cucumber6-adapter#15]
I have a cucumber test in which the scenario outline title is parameterised. After execution the parameterised value is getting populated in IDE test execution status but in extent reports it is blank.

Feature File : 

Scenario Outline: FreeCRM login scenario `'<username>'`

		Given User is on login page
		When Login page title is displayed
		Then user enters "<username>" and "<password>"
		Then user clicks on login button
		And user is navigated to HomePage
		And browser is closed

		Examples:
			| username | password |
			| testuser@gmail.com | test|

IDE result :
In the below snapshot, The scenario title is displayed as FreeCRM login scenario 'testuser@gmail.com' as expected.
 [
<img width="382" alt="Screenshot 2020-10-09 at 5 22 47 PM" src="https://user-images.githubusercontent.com/31689908/95580028-41a82000-0a54-11eb-9697-2ca0dec46579.png">
](url)

Extent Report Result : But in extent report it is FreeCRM login scenario ''. I am using 1.2.0 version. Please let me know how to resolve this issue. Am I missing some configuration?
<img width="999" alt="Screenshot 2020-10-09 at 5 27 05 PM" src="https://user-images.githubusercontent.com/31689908/95580347-ce52de00-0a54-11eb-8e3b-0ddfdda9d2ce.png">

**Comment by grasshopper7** [comment]
Yep this seems to be an issue. Will have a look.

**Comment by ritunegi04** [comment]
@grasshopper7 Sure. Thanks for quick response. Will look forward to hear from you regarding the resolution for this issue.

**Comment by ritunegi04** [comment]
@grasshopper7 Any update on this as we are using this plugin and have multiple parameterised scenarios so we would need this fix as soon as possible.

**Comment by grasshopper7** [comment]
Time permitting, will fix this today or tomorrow. Hope u realize that i volunteer for these open source contributions in my spare time, which in these 'covid days' is rare.
If it is urgent for your project u are welcome to fix this and send in a pull request.

**Comment by grasshopper7** [comment]
Fixed in version 2.1.0. Should be available in maven when synced.
