### ISSUE TITLE
Extra parent is being displayed for parameterised scenarios with blank parameterised value

### ISSUE THREAD

**Issue by ritunegi04** [grasshopper7/extentreports-cucumber6-adapter#17]
@grasshopper7 : Thanks for fixing the issue. But I am getting double quotes in Parameterised scenario outlines parent in version 2.1.0 : 

<img width="1197" alt="Screenshot 2020-10-15 at 12 37 33 PM" src="https://user-images.githubusercontent.com/31689908/96088584-44d35e00-0ee3-11eb-9e78-aedb212a4a8a.png">

Can we remove this scenario outline parent or ignore the double quotes .

Another issue which we observed is that this parameterised scenario outline parent appears in the tag reports and increases count of tests : 

<img width="1197" alt="Screenshot 2020-10-15 at 12 41 57 PM" src="https://user-images.githubusercontent.com/31689908/96089141-068a6e80-0ee4-11eb-9726-310bd945a851.png">

Here we have just parameterised one scenario but in our project where we have multiple parameterised scenarios, the count is increasing by a huge margin.

Can we please ignore this scenario outline parent from displaying in the tag report section.

My Feature File : 

```
@featureone
Feature: FreeCRM login feature

   @TestOne @Regression @Smoke @TestRun
	Scenario: Test increasedCount IssueOne

		Given User is on login pageOne
		When Login page title is displayedOne
		Then user enters uname and passwordOne
		Then user clicks on login buttonOne
		And user is navigated to HomePageOne
		And browser is closedOne
    @TestOne @Regression
	Scenario: Test increasedCount IssueTwo

		Given User is on login pageTwo
		When Login page title is displayedTwo
		Then user enters uname and passwordTwo
		Then user clicks on login buttonTwo
		And user is navigated to HomePageTwo
		And browser is closedTwo
	@Regression @Smoke
	Scenario: Test increasedCount IssueThree

		Given User is on login pageThree
		When Login page title is displayedThree
		Then user enters uname and passwordThree
		Then user clicks on login buttonThree
		And user is navigated to HomePageThree
		And browser is closedThree
	@Smoke
	Scenario: Test increasedCount IssueFour

		Given User is on login pageFour
		When Login page title is displayedFour
		Then user enters uname and passwordFour
		Then user clicks on login buttonFour
		And user is navigated to HomePageFour
		And browser is closedFour
	@TestOne
	Scenario: Test increasedCount IssueFive

		Given User is on login pageFive
		When Login page title is displayedFive
		Then user enters uname and passwordFive
		Then user clicks on login buttonFive
		And user is navigated to HomePageFive
		And browser is closedFive
@TestTwo
	Scenario: Test increasedCount IssueSix

		Given User is on login pageSix
		When Login page title is displayedSix
		Then user enters uname and passwordSix
		Then user clicks on login buttonSix
		And user is navigated to HomePageSix
		And browser is closedSix
	@TestTwo
	Scenario Outline: FreeCRM login scenario "<username>"

		Given User is on login page
		When Login page title is displayed
		Then user enters "<username>" and "<password>"
		Then user clicks on login button
		And user is navigated to HomePage
		And browser is closed

		Examples:
			| username | password |
			| testuser@gmail.com | test|


```

**Comment by grasshopper7** [comment]
Remove the double quotes in the scenario outline name - `FreeCRM login scenario <username>`. 

This is how Extent and spark report deals with scenario outline currently. It adds it to the total test count. U can raise this issue in the extentreports github page for the artifact developer feedback. https://github.com/extent-framework/extentreports-java

**Comment by grasshopper7** [comment]
Someone has already created an issue there - https://github.com/extent-framework/extentreports-java/issues/263.
