### ISSUE TITLE
Scenario Outline shows  Incorrect / Extra test  Count in Dashboard View - extentreports-cucumber6-adapter

### ISSUE THREAD

**Issue by bughunter7** [grasshopper7/extentreports-cucumber6-adapter#19]
When Running a Scenario Outline the count in the dashboard is incorrect . it displays double count to what scenario is executed also tags section shows same scenario title twice.

**Please find Below link for report screenshots –**
https://github.com/bughunter7/ExtentReportIssue

Dependency used –

**tech.grasshopper
extentreports-cucumber6-adapter
1.2.0
test**

![sc11](https://user-images.githubusercontent.com/55976995/96265766-7fbcbb00-0fe3-11eb-8446-b5d85f4d7924.png)

![sc22](https://user-images.githubusercontent.com/55976995/96265863-99f69900-0fe3-11eb-842c-3fc73cace127.png)

Please let me the solution its urgent .also let me know if any more info required from my end awaiting for your response 🙂

**Comment by grasshopper7** [comment]
How many rows do u have in the scenario outline? Add ur feature file. Is it double or just one additional test count?

**Comment by bughunter7** [comment]
Feature file I  am using has only one test count  - 

 Feature: Backend Order Creation
 
  @Checkout
  Scenario Outline: User Creates an order From Backend
    Given user is on Landing Page
    When he enters his username and password to test OrderCreation TC
    And clicks on sales
    And clicks on orders
    And clicks on create new order
    Then he enters the <email id> and <userid>
    And clicks on search button
    And clicks on search results
    Then selects  as a store
    And clicks on add products
    Then searches for <sku>
    And selects the product from checkbox
    And clicks on add selected products to order
    And enters the purchase order no <po number>
    And clicks on link get shipping methods and rates
    And selects the radio button
    And clicks on submit order
    Then message visible is you created the order
    And order no is displayed

    Examples: 
      | email id              | userid | sku                                    | po number |
      | tomailior.com    |     70   | 00-2118860-4-106-a0820 |      1234       |

**Comment by grasshopper7** [comment]
The adapter collects and sends the data to the existing Extent Spark Report which applies the logic for report creation.
If the data collection logic is changed at the adapter level by ignoring the scenario outline then the report will not display the scenarios under a scenario outline but as independent scenarios. Pretty sure there would be other consequences. My understanding is that this needs to be looked at from the Extent Report level. As you have already created a similar issue in that repo, it would be my suggestion to get their feedback on this.
