### ISSUE TITLE
Option to default your report to Dashboard

### ISSUE THREAD

**Issue by tbc-home** [grasshopper7/extentreports-cucumber6-adapter#21]
Is there a way to default your report to Dashboard screen when opened? I am using ExtentReport cucumber 6 adapter 2.0.0 version.

**Comment by grasshopper7** [comment]
Added in 2.2.0

**Comment by grasshopper7** [comment]
Details can be found at https://grasshopper.tech/2098/. search for 'Spark Report View Order'
