### ISSUE TITLE
BDD Keywords are not bolded or highlighted, Previous version they use to come as bolded. 

### ISSUE THREAD

**Issue by tbc-home** [grasshopper7/extentreports-cucumber6-adapter#22]
BDD Keywords are not bolded or highlighted, Previous version they use to come as bolded or colored. 

![image](https://user-images.githubusercontent.com/28675824/96472382-08d72a80-124e-11eb-86ce-cd43199ac11a.png)

**Comment by grasshopper7** [comment]
U will have to check with the extentreport developer. I can look at data or content issues in the report but almost all of the time presentation or view issues I cannot address. Thx
