### ISSUE TITLE
Example to add console output in cucumber reports

### ISSUE THREAD

**Issue by SonaliSihra** [grasshopper7/extentreports-cucumber6-adapter#30]
@grasshopper7 
I'm using the same version of cucumber and reports as shown in README and i have a requirement to show console logs in HTML report due to which the step failed. Is this feature available ? Can you please some example to do that? I'm using Junit for support.

**Comment by grasshopper7** [comment]
The report displays the exception stacktrace of the failure in the test details tab. Not sure I understand completely. Can u add some more details about your requirement? Are u referring the Spark report as the HTML report is deprecated.

**Comment by SonaliSihra** [comment]
> The report displays the exception stacktrace of the failure in the test details tab. Not sure I understand completely. Can u add some more details about your requirement? Are u referring the Spark report as the HTML report is deprecated.

Yes, currently I'm using spark html report. I'll try to explain my requirements from an example. Suppose there is one get api and I was asserting for 200 status code but for some backend error it is throwing error. That assert failed and shown as step failed in report. But my senior wants us to display the exact error message returned by that api for better representation.
If this report is deprecated, there is any other way to do the same?

**Comment by grasshopper7** [comment]
U are using the correct report - Spark.
Catch the original exception when response is not 200 and throw it again. The report should display the exception stacktrace.

**Comment by SonaliSihra** [comment]
The report is just throwing assertion exception not the response ones. Can you please share an example on how to throw them to report?

**Comment by grasshopper7** [comment]
Would be easier if u add the relevant step definition code lines here.

**Comment by SonaliSihra** [comment]
```
    @Given("Incorrect token is sent on user")
    public void incorrectTokenIsSentOnUser() {
        RestAssured.baseURI = loadTestData.getString("STG");
        String path = RestAssured.baseURI + "/user";

        values.put("access_token", loadTestData.getString("IncorrectToken"));

        Response res = CommonMethods.getRequest(path, values, headers);
        actualMessage = res.path("message");
        responseCode = res.statusCode();
```
```
    @Then("Error message is {string}")
    public void errorMessageIs(String message) {
        CommonMethods.verifyEquals(actualMessage, message, "Comparing unauthorized error message");
        CommonMethods.verifyEquals(responseCode, 401, "Comparing unauthorized error status code");
    }

```
Scenario for the same is:
  @stg
  Scenario: Check error message for incorrect token on /user
    Given Incorrect token is sent on user
    Then Error message is "Unauthorized"

Now here if for some reason my setp failed the report only shows the assertion error for example:
![image](https://user-images.githubusercontent.com/50992346/101753621-e0a2d400-3af8-11eb-8d06-f25944998c7a.png)

Here, Along with this i want to add error message shared by the api (due to which the test failed) so that it can bring more clarity to the team. I'm printing them on my console and wanted some guidance to the same on reports.

**Comment by SonaliSihra** [comment]
Also, if this is not possible i have a LogFile.log in which i'm printing the responses is there any chance to add the logfile to the report so that the teams can take reference from it? I'm suggesting this is as a alternative from the above situation.

**Comment by grasshopper7** [comment]
Looks like this code line is setting up - `Response res = CommonMethods.getRequest(path, values, headers);` On failure this throws an unchecked exception. If this correct, then u can surround this line with a try catch block and throw the exception again. Cucumber will fail this Given step instead of performing any further comparison steps.

**Comment by grasshopper7** [comment]
I am not that familiar with API testing, so these maybe dumb queries. Are these error messages in the console from the API in a separate process? If the test code is generating this logfile then u can use the error message to raise a runtime exception.  Is this the code which should error if the server has an issue - `Response res = CommonMethods.getRequest(path, values, headers);`

**Comment by SonaliSihra** [comment]
@grasshopper7 Sharing code for that part:
```
    public static Response getRequest(String getPath, Map<String, String> values, Map<String, String> headers) {
        //Log.logInfo("sending GET request");
        Response jsonResponse = null;
        Log.logInfo(getPath);
        try {
            jsonResponse =
                    given()
                            .params(values)
                            .headers(headers)
                            .when()
                            .get(getPath);
        } catch (Exception e) {
            Log.logError("CommonMethods", "getRequest", "Exception occurred: " + e);
        }

        assert jsonResponse != null;
        Log.logInfo("getRequest response: " + jsonResponse.asString());
        return jsonResponse;

    }
```

**Comment by grasshopper7** [comment]
Rethrow the exception from the `getRequest()` method. U can use any other custom exception from ur project also.

```
} catch (Exception e) {
            Log.logError("CommonMethods", "getRequest", "Exception occurred: " + e);
           throw new RuntimeException(e);
 }
```

**Comment by SonaliSihra** [comment]
I tried with your suggestion and end up doing this in my step def to get desired results:
        if (!success) {
            String message = res.path("message");
            throw new CucumberBackendException(message);
        }
Thanks for your support @grasshopper7 .
