### ISSUE TITLE
How can I add My CSS Styles to extent report?

### ISSUE THREAD

**Issue by GoldenGuts** [grasshopper7/extentreports-cucumber6-adapter#32]
Hello, I've been trying to make some changes in the extent report using css, after doing them in browser and make changes permanent I'm trying to put the css style in the xml file under <styles> but it is not working. How can I change the css? 
I even tried linking the css with extent.properties extent.reporter.spark.config.CSS followed by the css file name...

**Comment by grasshopper7** [comment]
Sorry missed the issue. Adding the css style in xml should work. Have u tried this with extent reports without the adapter? Will have a look.

**Comment by GoldenGuts** [comment]
yea, i made it work with xml, put styles under cdata
