### ISSUE TITLE
Screenshots not getting added to extent report even after adding the screenshot.dir property

### ISSUE THREAD

**Issue by JaydipPatel2009** [grasshopper7/extentreports-cucumber6-adapter#46]
Hello @anshooarora and @grasshopper7 , I am using the cucumber6 dependency as mentioned below. and also below is my folder structure and property file. Somehow its not placing screenshots at the location mentioned in property file and also not attaching same to report. please advise if there is something wrong.

<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber6-adapter</artifactId>
			<version>2.8.4</version>
</dependency>

![image](https://user-images.githubusercontent.com/48186367/134634634-a5921659-fba0-4dbd-9af1-a04fd4c5776f.png)

**Comment by grasshopper7** [comment]
U have set the base64 image to true. With this setting, no physical image file will be created. A 'base64 img' thumbnail will be added, which when clicked a larger image will be displayed.
Set this setting to false or comment it. This should create the physical files.

**Comment by grasshopper7** [comment]
Share your repository with minimum code which reproduces the issue, will have a look

**Comment by JaydipPatel2009** [comment]
@grasshopper7 here is the URI https://github.com/JaydipPatel2009/ExtentSpartReport.git

**Comment by JaydipPatel2009** [comment]
@grasshopper7 let me know if you find anything that is not compatible. I tried with adapter7 and did not work. Also tried Cucumber version 6.10.2 but it did not work with that either.

**Comment by grasshopper7** [comment]
There is no code which is taking screenshot.

```
TakesScreenshot ts = (TakesScreenshot) driver;
byte[] screenshot = ts.getScreenshotAs(OutputType.BYTES);
scenario.attach(screenshot, "image/png", "");
```
U should check out the sample implementation referred earlier for more details.

![embedded1](https://user-images.githubusercontent.com/10829355/135039316-802f36d4-3829-4eff-98ec-88a3bc4c08c0.png)
![embedded2](https://user-images.githubusercontent.com/10829355/135039336-c33ce84f-cc98-4a67-8645-0b809f0d7d85.png)

[ExtentPdf.pdf](https://github.com/grasshopper7/extentreports-cucumber6-adapter/files/7241855/ExtentPdf.pdf)
[reports.zip](https://github.com/grasshopper7/extentreports-cucumber6-adapter/files/7241856/reports.zip)

If this is production code then it needs to be refactored with how the driver is shared between runners, steps and pages. Also the testng runner just needs to inherit from AbstractTestNGRunner, no need for adding methods.

**Comment by JaydipPatel2009** [comment]
Thanks for the input @grasshopper7  but where would you put this code? under @test in runner ? or under @afterStep in step definition ? also the extent.property file was correctly written?

**Comment by grasshopper7** [comment]
in afterstep and add a condition to only run if scenario fails, if that is the requirement. extent.property is correct.

**Comment by JaydipPatel2009** [comment]
@grasshopper7 I was able to implement it. Thanks a lot for the guidance and help. Only thing is probably I will have to add little bit of wait time as the thread is taking screenshots very quickly and sometimes if the web page has latency in terms of loading all web elements, it could take improper screenshots. 

Appreciate the help. 

I will be closing this issue. I will update repo with updated code base.

**Comment by JaydipPatel2009** [comment]
Hi @grasshopper7 I am reopening the thread as I have one more question. Once I attach the screenshot, the report shows the image fine if opened from local. but for my requirement, I need to send the report to JIRA as an attachment, so once I download from JIRA and open that downloaded report I see the image broken. How can I handle that part?

**Comment by JaydipPatel2009** [comment]
Got it. Base64 is the way to do it.
