### ISSUE TITLE
I can't add photos to the extent report

### ISSUE THREAD

**Issue by York6666** [grasshopper7/extentreports-cucumber6-adapter#6]
Hi. Is there a way to save the photos in each step that is made?
I currently have this

![image](https://user-images.githubusercontent.com/48634709/88078422-1511f580-cb42-11ea-811b-209c468bfd88.png)

and my extent report settings are this

![image](https://user-images.githubusercontent.com/48634709/88078568-3a066880-cb42-11ea-9322-a65208ef8a69.png)

when executing if you save the photo but save it on my desktop and I do not know why

![image](https://user-images.githubusercontent.com/48634709/88078697-60c49f00-cb42-11ea-824f-e48e60a0885b.png)

please i would like to see the way to add the photos to the report

**Comment by grasshopper7** [comment]
Can u share the code in a repository?

**Comment by York6666** [comment]
> Can u share the code in a repository?

**Comment by York6666** [comment]
> Can u share the code in a repository?

https://github.com/York6666/ExtentReport

this is !!!

**Comment by York6666** [comment]
@grasshopper7  hello anything you want to consult me ​​let me know, Thank u!!

**Comment by grasshopper7** [comment]
Sent a PR to your repo. Merge it and try.

**Comment by York6666** [comment]
> Sent a PR to your repo. Merge it and try.

ok now i try it, can i take a photo for each step?

**Comment by York6666** [comment]
thank you very much I was able to solve everything !! thank you again @grasshopper7
