### ISSUE TITLE
Unable to attach the Screenshot to the report

### ISSUE THREAD

**Issue by gbalaji94** [grasshopper7/extentreports-cucumber6-adapter#7]
Hi @grasshopper7 

I am using the below code to attach the screenshot to the report, but in the report the image is empty, Can you please help?

    @After
    public void addScreenshotsToReport(Scenario scenario) {
        if (scenario.isFailed()) {
            byte[] screenshot = ((TakesScreenshot) baseDriver.driver).getScreenshotAs(OutputType.BYTES);
            scenario.attach(screenshot, "image/png", scenario.getName());
        }
    }

**Comment by grasshopper7** [comment]
Do u have the screenshot properties in the extent.properties? Can u add the extent.properties here?

```
screenshot.dir=test-output/
screenshot.rel.path=../
```

**Comment by gbalaji94** [comment]
I found the issue and fixed. Thanks 👍 

Code and Properties here : 

`    @After
    public void addScreenshotsToReport(Scenario scenario) throws IOException {
        if (scenario.isFailed()) {
            byte[] screenshot = ((TakesScreenshot) baseDriver.driver).getScreenshotAs(OutputType.BYTES);
            scenario.attach(screenshot, "image/png", scenario.getName());
        }
    }`


`screenshot.dir=test-output/screenshots
screenshot.rel.path=./screenshots/`
